[project]
name = "google"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "google-api-python-client>=2.188.0",
    "google-auth-oauthlib>=1.2.4",
    "google-cloud-bigquery>=3.40.0",
    "google-cloud-logging>=3.13.0",
]
